"""empty message

Revision ID: 573d1b06278b
Revises: 71dcff6540d0
Create Date: 2025-02-28 15:36:31.240278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573d1b06278b'
down_revision = '71dcff6540d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guitar_code', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guitar_code', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
